version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: pix_wallet_db
    environment:
      POSTGRES_DB: pix_wallet
      POSTGRES_USER: stark
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stark -d pix_wallet"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: